name: homelab
services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.sarsha.co.il"
    volumes:
      - ${TOOLS_VOL}/vaultwarden/:/data/
    ports:
      - 1711:80