services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=1721
      - TORRENTING_PORT=6881
    volumes:
      - ${STORAGE_VOL}/qbittorrent/config:/config
      - media-smb:/media #optional
    ports:
      - 1721:1721
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped