name: homelab
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    ports:
      - 1704:8096
    volumes:
      - ${VOLUMES_DIRECTORY}/multimedia/jellyfin/config:/config
      - ${VOLUMES_DIRECTORY}/multimedia/jellyfin/cache:/cache
      - media-smb:/media
    restart: always