name: homelab
services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ${HOME_AUTO_VOL}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 1712:8080
    environment:
      - TZ=${TZ}
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyACM0
