name: homelab
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MULTIMEDIA_VOL}/bazarr/config:/config
      - media-smb:/media #optional
    ports:
      - 1718:6767
    restart: unless-stopped