name: homelab
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
#    security_opt:
#      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${INFRA_VOL}/cf-ddns/config.json:/config.json
    restart: always